[ColorScheme]
active_colors=#ff8BA7A7, #ff070216, #ff3A4A5C, #ff2A3A4C, #ff0E1A28, #ff4A6B7C, #ff8BA7A7, #ff8BA7A7, #ff8BA7A7, #ff070216, #ff090318, #ff0A1520, #ff2D4A5C, #ff8BA7A7, #ff61E2FF, #ffAF6DF9, #ff2D4A5C, #ff090318, #ff8BA7A7, #ff495495, #80ffffff
disabled_colors=#ff495495, #ff070216, #ff3A4A5C, #ff2A3A4C, #ff0E1A28, #ff4A6B7C, #ff495495, #ff8BA7A7, #ff495495, #ff070216, #ff090318, #ff0A1520, #ff2D4A5C, #ff495495, #ff61E2FF, #ffAF6DF9, #ff2D4A5C, #ff090318, #ff495495, #ff495495, #80ffffff
inactive_colors=#ff8BA7A7, #ff070216, #ff3A4A5C, #ff2A3A4C, #ff0E1A28, #ff4A6B7C, #ff8BA7A7, #ff8BA7A7, #ff8BA7A7, #ff070216, #ff090318, #ff0A1520, #ff2D4A5C, #ff8BA7A7, #ff61E2FF, #ffAF6DF9, #ff2D4A5C, #ff090318, #ff8BA7A7, #ff495495, #80ffffff

[Appearance]
custom_palette=true
icon_theme=candy-icons
standard_dialogs=default
style=kvantum-dark

[Fonts]
fixed="Hack Nerd Font Mono,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Rubik,12,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3

[PaletteEditor]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85\0\0\0\0\0\0\0\0\a\x80\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85)

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85\0\0\0\0\0\0\0\0\a\x80\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85)

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()
