[ColorScheme]
active_colors=#ff2D2D2D, #ffF5F5F5, #ffFFFFFF, #ffF8F8F8, #ffE5E7EB, #ffD1D5DB, #ff2D2D2D, #ff2D2D2D, #ff2D2D2D, #ffF5F5F5, #ffFAFAFA, #ffD1D5DB, #ffE5E7EB, #ff2D2D2D, #ff0891B2, #ff7C3AED, #ffE5E7EB, #ffFAFAFA, #ff2D2D2D, #ff9CA3AF, #80ffffff
disabled_colors=#ff9CA3AF, #ffF5F5F5, #ffFFFFFF, #ffF8F8F8, #ffE5E7EB, #ffD1D5DB, #ff9CA3AF, #ff2D2D2D, #ff9CA3AF, #ffF5F5F5, #ffFAFAFA, #ffD1D5DB, #ffE5E7EB, #ff9CA3AF, #ff0891B2, #ff7C3AED, #ffE5E7EB, #ffFAFAFA, #ff9CA3AF, #ff9CA3AF, #80ffffff
inactive_colors=#ff2D2D2D, #ffF5F5F5, #ffFFFFFF, #ffF8F8F8, #ffE5E7EB, #ffD1D5DB, #ff2D2D2D, #ff2D2D2D, #ff2D2D2D, #ffF5F5F5, #ffFAFAFA, #ffD1D5DB, #ffE5E7EB, #ff2D2D2D, #ff0891B2, #ff7C3AED, #ffE5E7EB, #ffFAFAFA, #ff2D2D2D, #ff9CA3AF, #80ffffff

[Appearance]
custom_palette=true
icon_theme=Papirus
standard_dialogs=default
style=kvantum

[Fonts]
fixed="Hack Nerd Font Mono,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"
general="Rubik,10,-1,5,400,0,0,0,0,0,0,0,0,0,0,1"

[Interface]
activate_item_on_single_click=1
buttonbox_layout=0
cursor_flash_time=1000
dialog_buttons_have_icons=1
double_click_interval=400
gui_effects=@Invalid()
keyboard_scheme=2
menus_have_icons=true
show_shortcuts_in_context_menus=true
stylesheets=@Invalid()
toolbutton_style=4
underline_shortcut=1
wheel_scroll_lines=3

[PaletteEditor]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85\0\0\0\0\0\0\0\0\a\x80\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85)

[SettingsWindow]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85\0\0\0\0\0\0\0\0\a\x80\0\0\x2\x80\0\0\x1\x44\0\0\x5\x7f\0\0\x3\x85)

[Troubleshooting]
force_raster_widgets=1
ignored_applications=@Invalid()
